/**
 * Error codes returned from the backend API or generated client-side
 */
export const ErrorCodes = {
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED', // Client-side code generated from 401 status

  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_NOT_NULL_ERROR: 'VALIDATION_NOT_NULL_ERROR',
  VALIDATION_NOT_EMPTY_ERROR: 'VALIDATION_NOT_EMPTY_ERROR',
  VALIDATION_MAX_LENGTH_ERROR: 'VALIDATION_MAX_LENGTH_ERROR',
  VALIDATION_MAX_VALUE_EXCEEDED_ERROR: 'VALIDATION_MAX_VALUE_EXCEEDED_ERROR',
  VALIDATION_MINVALUE_NOT_MATCHED_ERROR: 'VALIDATION_MINVALUE_NOT_MATCHED_ERROR',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  ENTITY_ALREADY_EXISTS: 'ENTITY_ALREADY_EXISTS',
  VALIDATION_NOT_ENUM_PROPERTY: 'VALIDATION_NOT_ENUM_PROPERTY',
  BAD_REQUEST_ERROR: 'BAD_REQUEST_ERROR',
  ORDER_ALREADY_ASSIGNED_TO_OUTGOING_SHIPMENT: 'ORDER_ALREADY_ASSIGNED_TO_OUTGOING_SHIPMENT',
  SHIPMENT_NOT_PREPARED: 'SHIPMENT_NOT_PREPARED',
  SHIPMENT_CANNOT_BE_LOADED_WITHOUT_STOPS: 'SHIPMENT_CANNOT_BE_LOADED_WITHOUT_STOPS',
  SHIPMENT_ALREADY_DELIVERED: 'SHIPMENT_ALREADY_DELIVERED',
  SHIPMENT_ALREADY_CANCELLED: 'SHIPMENT_ALREADY_CANCELLED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
